name: practice for the GitHub Actions

on: 
  push:
    branches:
      - main

jobs:
  Checking:
    runs-on: python3-latest
    steps: 
      - name: Checking out the code
        uses: actions/checkout@v2
      - run: python3 main.py

  output: 
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo "sucess"
